version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly' # Can be daily, weekly, or monthly
      open-pull-requests-limit: 10
      reviewers:
          - 'anonymous-sidhax'
      labels:
          - 'dependencies'
      commit-message:
          prefix: 'update(deps):'
          include: 'scope'
